In [7]:
import numpy as np
a = 1.2500001
b = np.array([[1.6245],
[1],
[1]])


c = 0.292134 
d = np.array([[2.2943],
[1],
[1]])



print(np.dot(a,b))
print(np.dot(c,d))

print(np.dot(a,b) + np.dot(c,d))


[[2.03062516]
 [1.2500001 ]
 [1.2500001 ]]
[[0.67024304]
 [0.292134  ]
 [0.292134  ]]
[[2.7008682]
 [1.5421341]
 [1.5421341]]
