### **Preprocessing**

**Case Folding**

In [2]:
ulasan_1 = "Saya paling senang blnja online disini,slama 7thn blnja disini gk pernah tertipu,sellernya jujur2 & ramah serta CS nya juga sopan klo kita ada kendala. Beda ama toko online shop sebelah saya 2x ketipu dionline shop sebelah 2 online shope.. disini saya nyaman blnja apapun itu.... cuma 1 yg bikin kesal tentang SERBU SERU blm prnh dpt barang 😂😂😂"
ulasan_2 = "aplikasi bermanfaat. sangat membantu di jaman now. mudah dan cepat" 
ulasan_3 = "top banget dah fitur dan harganya bener2 sangat bermanfaat sukses selalu untuk bukalapak excelent nomor wahid" 
ulasan_4 = "Pelayanan bukalapak untuk penjual sangat jelek, bukadompet saya dibekukan udah beberapa hari ini padahal udah komplain berulang kali dan memberikan bukti transaksi yang valid tapi tetep aja masih dibekukan dan hasil penjualan jadi ditahan, mohon aktifkan kembali bukadompet saya!!!" 
ulasan_5 = "Bukalapak bagus barang sesuai pengiriman cepat...tingkatkan min biar makin semangat belanja d bukalapak nya wkwkwk" 

print(f"""Contoh Data Ulasan:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5} 
""")

def case_folding(teks):
    teks = teks.lower()
    return teks

ulasan_1 = case_folding(ulasan_1)
ulasan_2 = case_folding(ulasan_2)
ulasan_3 = case_folding(ulasan_3)
ulasan_4 = case_folding(ulasan_4)
ulasan_5 = case_folding(ulasan_5)

print("="*130, '\n')
print(f"""Setelah Case Folding:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5}
""")

Contoh Data Ulasan:
Saya paling senang blnja online disini,slama 7thn blnja disini gk pernah tertipu,sellernya jujur2 & ramah serta CS nya juga sopan klo kita ada kendala. Beda ama toko online shop sebelah saya 2x ketipu dionline shop sebelah 2 online shope.. disini saya nyaman blnja apapun itu.... cuma 1 yg bikin kesal tentang SERBU SERU blm prnh dpt barang 😂😂😂 

aplikasi bermanfaat. sangat membantu di jaman now. mudah dan cepat 

top banget dah fitur dan harganya bener2 sangat bermanfaat sukses selalu untuk bukalapak excelent nomor wahid 

Pelayanan bukalapak untuk penjual sangat jelek, bukadompet saya dibekukan udah beberapa hari ini padahal udah komplain berulang kali dan memberikan bukti transaksi yang valid tapi tetep aja masih dibekukan dan hasil penjualan jadi ditahan, mohon aktifkan kembali bukadompet saya!!! 

Bukalapak bagus barang sesuai pengiriman cepat...tingkatkan min biar makin semangat belanja d bukalapak nya wkwkwk 


Setelah Case Folding:
saya paling senang blnja onl

**Filtering**

In [3]:
import re
import string

# filtering
def filtering(teks):

    # Step 1 - Menghilangkan url
    teks = re.sub(r'http\S+', '', teks)
    teks = re.sub(r'https\S+', '', teks)

    # Step 2 - Menghilangkan spasi dan tanda baca kecuali underscore
    teks = re.sub(r'''         
                \W+ 
                \s*     
                ''',    
                ' ',    
                teks,
                flags=re.VERBOSE)

    # Step 3 - Menghilangkan angka
    teks = ' '.join(re.sub(r"\d+", "", teks).split())

    # Step 4 - Menghilangkan Unicode, spasi tab, dan, new line 
    teks = teks.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ")   

    # Step 5 - Encoding dan decode ascii (konversi byte)
    teks = teks.encode('ascii', 'replace').decode('ascii')
    
    # Step 6 - menghilangkan white space lebih
    teks = ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", teks).split())

    hilangkan_tanda_baca = string.punctuation

    # Step 7 - menghilangkan semua tanda baca
    teks = teks.translate(str.maketrans(' ', ' ', hilangkan_tanda_baca))

    # Step 8 - Menghilangkan satu karakter
    teks = re.sub(r"\b[a-zA-Z]\b", "", teks)
    return teks


print(f"""Sebelum Filtering:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5} 
""")

ulasan_1 = filtering(ulasan_1)
ulasan_2 = filtering(ulasan_2)
ulasan_3 = filtering(ulasan_3)
ulasan_4 = filtering(ulasan_4)
ulasan_5 = filtering(ulasan_5)

print("="*130, '\n')
print(f"""Setelah Filtering:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5}
""")


Sebelum Filtering:
saya paling senang blnja online disini,slama 7thn blnja disini gk pernah tertipu,sellernya jujur2 & ramah serta cs nya juga sopan klo kita ada kendala. beda ama toko online shop sebelah saya 2x ketipu dionline shop sebelah 2 online shope.. disini saya nyaman blnja apapun itu.... cuma 1 yg bikin kesal tentang serbu seru blm prnh dpt barang 😂😂😂 

aplikasi bermanfaat. sangat membantu di jaman now. mudah dan cepat 

top banget dah fitur dan harganya bener2 sangat bermanfaat sukses selalu untuk bukalapak excelent nomor wahid 

pelayanan bukalapak untuk penjual sangat jelek, bukadompet saya dibekukan udah beberapa hari ini padahal udah komplain berulang kali dan memberikan bukti transaksi yang valid tapi tetep aja masih dibekukan dan hasil penjualan jadi ditahan, mohon aktifkan kembali bukadompet saya!!! 

bukalapak bagus barang sesuai pengiriman cepat...tingkatkan min biar makin semangat belanja d bukalapak nya wkwkwk 


Setelah Filtering:
saya paling senang blnja online 

**Word Normalization**

In [4]:
import pandas as pd

kamus_informal_to_formal = pd.read_csv('kamus_normalization.tsv',sep='\t')
kamus_informal_to_formal = kamus_informal_to_formal.iloc[:,1:3]


kamus_normalisasi = {}

# penambahan yang tidak ada di kamus sebelumnya, wahid -> satu
kamus_normalisasi = {"x": "kali", "now": "sekarang", "min": "admin"}

for index, row in kamus_informal_to_formal.iterrows():
    if row[0] not in kamus_normalisasi:
        kamus_normalisasi[row[0]] = row[1]


# kamus_normalisasi # tampilkan kamus

# convert string to list of words
def word_normalization(teks):
    # mensplit
    teks = teks.split()

    teks = [kamus_normalisasi[word] if word in kamus_normalisasi else word for word in teks]

    teks = ' '.join(teks)

    return teks


print(f"""Sebelum Word Normalization:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5} 
""")

ulasan_1 = word_normalization(ulasan_1)
ulasan_2 = word_normalization(ulasan_2)
ulasan_3 = word_normalization(ulasan_3)
ulasan_4 = word_normalization(ulasan_4)
ulasan_5 = word_normalization(ulasan_5)

print("="*130, '\n')
print(f"""Setelah Word Normalization:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5}
""")

Sebelum Word Normalization:
saya paling senang blnja online disini slama thn blnja disini gk pernah tertipu sellernya jujur ramah serta cs nya juga sopan klo kita ada kendala beda ama toko online shop sebelah saya  ketipu dionline shop sebelah online shope disini saya nyaman blnja apapun itu cuma yg bikin kesal tentang serbu seru blm prnh dpt barang 

aplikasi bermanfaat sangat membantu di jaman now mudah dan cepat 

top banget dah fitur dan harganya bener sangat bermanfaat sukses selalu untuk bukalapak excelent nomor wahid 

pelayanan bukalapak untuk penjual sangat jelek bukadompet saya dibekukan udah beberapa hari ini padahal udah komplain berulang kali dan memberikan bukti transaksi yang valid tapi tetep aja masih dibekukan dan hasil penjualan jadi ditahan mohon aktifkan kembali bukadompet saya 

bukalapak bagus barang sesuai pengiriman cepat tingkatkan min biar makin semangat belanja  bukalapak nya wkwkwk 


Setelah Word Normalization:
saya paling senang belanja online di sini sela

**Convert Negation**

In [5]:
# kata tak
def convert_negation(teks):
    convert_tidak = teks.replace("tidak ", "tidak_")
    convert_belum = convert_tidak.replace("belum ", "belum_")
    convert_jangan = convert_belum.replace("jangan ", "jangan_")
    convert_tak = convert_jangan.replace("tak ", "tak_")
    last_convert = convert_tak.replace("bukan ", "bukan_")

    return last_convert

print(f"""Sebelum Convert Negation:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5} 
""")

ulasan_1 = convert_negation(ulasan_1)
ulasan_2 = convert_negation(ulasan_2)
ulasan_3 = convert_negation(ulasan_3)
ulasan_4 = convert_negation(ulasan_4)
ulasan_5 = convert_negation(ulasan_5)

print("="*130, '\n')
print(f"""Setelah Convert Negation:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5}
""")

Sebelum Convert Negation:
saya paling senang belanja online di sini selama tahun belanja di sini tidak pernah tertipu penjualnya jujur ramah serta layanan pelanggan nya juga sopan kalau kita ada kendala beda sama toko online shop sebelah saya tertipu dionline shop sebelah online shope di sini saya nyaman belanja apapun itu cuma yang membuat kesal tentang serbu seru belum pernah dapat barang 

aplikasi bermanfaat sangat membantu di jaman sekarang mudah dan cepat 

top sangat sudah fitur dan harganya benar sangat bermanfaat sukses selalu untuk bukalapak excelent nomor wahid 

pelayanan bukalapak untuk penjual sangat jelek bukadompet saya dibekukan sudah beberapa hari ini padahal sudah komplain berulang kali dan memberikan bukti transaksi yang valid tapi tetap saja masih dibekukan dan hasil penjualan jadi ditahan mohon aktifkan kembali bukadompet saya 

bukalapak bagus barang sesuai pengiriman cepat tingkatkan admin biar makin semangat belanja bukalapak nya hahaha 


Setelah Convert Negat

**Tokenization**

In [6]:
from nltk.tokenize import word_tokenize

def tokenization(teks):
    teks = word_tokenize(teks)
    return teks

print(f"""Sebelum Tokenization:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5} 
""")

ulasan_1 = tokenization(ulasan_1)
ulasan_2 = tokenization(ulasan_2)
ulasan_3 = tokenization(ulasan_3)
ulasan_4 = tokenization(ulasan_4)
ulasan_5 = tokenization(ulasan_5)

print("="*130, '\n')
print(f"""Setelah Tokenization:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5}
""")

Sebelum Tokenization:
saya paling senang belanja online di sini selama tahun belanja di sini tidak_pernah tertipu penjualnya jujur ramah serta layanan pelanggan nya juga sopan kalau kita ada kendala beda sama toko online shop sebelah saya tertipu dionline shop sebelah online shope di sini saya nyaman belanja apapun itu cuma yang membuat kesal tentang serbu seru belum_pernah dapat barang 

aplikasi bermanfaat sangat membantu di jaman sekarang mudah dan cepat 

top sangat sudah fitur dan harganya benar sangat bermanfaat sukses selalu untuk bukalapak excelent nomor wahid 

pelayanan bukalapak untuk penjual sangat jelek bukadompet saya dibekukan sudah beberapa hari ini padahal sudah komplain berulang kali dan memberikan bukti transaksi yang valid tapi tetap saja masih dibekukan dan hasil penjualan jadi ditahan mohon aktifkan kembali bukadompet saya 

bukalapak bagus barang sesuai pengiriman cepat tingkatkan admin biar makin semangat belanja bukalapak nya hahaha 


Setelah Tokenization:
['s

**Stopword Removal**

In [7]:
from nltk.corpus import stopwords
STOPWORDS = stopwords.words('indonesian')
# print(STOPWORDS)
STOPWORDS.extend(['kali', 'nya'])
# STOPWORDS.extend(['amp','hahaha','ya','bnr','bener','iya','dikit','sih','nya', 'yg', 'dll','gara', 'dan lain', 'dan lain-lain', 'oh','y','g','yes', 'yang','gak','bgt','ku','buat','karena','karna','ga','udah','udh','pas','kalau','kalo','eh','deh','coba','oke','a','aa','aaa','aaaa','aaaaa','huhuhu','hihihi','hahaha','hehehe','he','heh','hehe','si','ah','aja','ni','ini','xixi','da'])

stopword_list = set(STOPWORDS)

# Kata yang tidak seharusnya dibuang : membuat, dapat
# stopword_list.remove("dapat")

def stopword_removal(teks):
    stopword = []

    for word in teks:
        if word not in stopword_list:
            stopword.append(word)
    return stopword

print(f"""Sebelum Stopword Removal:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5} 
""")

ulasan_1 = stopword_removal(ulasan_1)
ulasan_2 = stopword_removal(ulasan_2)
ulasan_3 = stopword_removal(ulasan_3)
ulasan_4 = stopword_removal(ulasan_4)
ulasan_5 = stopword_removal(ulasan_5)

print("="*130, '\n')
print(f"""Setelah Stopword Removal:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5}
""")

Sebelum Stopword Removal:
['saya', 'paling', 'senang', 'belanja', 'online', 'di', 'sini', 'selama', 'tahun', 'belanja', 'di', 'sini', 'tidak_pernah', 'tertipu', 'penjualnya', 'jujur', 'ramah', 'serta', 'layanan', 'pelanggan', 'nya', 'juga', 'sopan', 'kalau', 'kita', 'ada', 'kendala', 'beda', 'sama', 'toko', 'online', 'shop', 'sebelah', 'saya', 'tertipu', 'dionline', 'shop', 'sebelah', 'online', 'shope', 'di', 'sini', 'saya', 'nyaman', 'belanja', 'apapun', 'itu', 'cuma', 'yang', 'membuat', 'kesal', 'tentang', 'serbu', 'seru', 'belum_pernah', 'dapat', 'barang'] 

['aplikasi', 'bermanfaat', 'sangat', 'membantu', 'di', 'jaman', 'sekarang', 'mudah', 'dan', 'cepat'] 

['top', 'sangat', 'sudah', 'fitur', 'dan', 'harganya', 'benar', 'sangat', 'bermanfaat', 'sukses', 'selalu', 'untuk', 'bukalapak', 'excelent', 'nomor', 'wahid'] 

['pelayanan', 'bukalapak', 'untuk', 'penjual', 'sangat', 'jelek', 'bukadompet', 'saya', 'dibekukan', 'sudah', 'beberapa', 'hari', 'ini', 'padahal', 'sudah', 'komplain'

**Stemming**

In [8]:
# Stemming
# from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
# factory = StemmerFactory()
# stemmer = factory.create_stemmer()

# kalimat = "'bagus', 'banget', 'kedepannya', 'tolong', 'tingkatkan', 'tampilan', 'ui', 'nya', 'kenyamanan', 'belanja', 'meningkat'"
# hasil = stemmer.stem(kalimat)
# word_tokens = word_tokenize(hasil)
# print(word_tokens)

# ouput
# andi kerap laku transaksi rutin cara daring atau online turut andi belanja online lebih praktis murah

### **Word Embedding**

In [9]:
import io
import tqdm

import numpy as np
import tensorflow as tf

from tensorflow.keras import layers

**Penambahan Token Aspek**

In [10]:
# Membuat Token aspek
token_aspek = ['<LAYANAN>', '<FITUR>', '<KEBERMANFAATAN>', '<BISNIS>', '<NON ASPEK>']

print(f"""Sebelum Stopword Removal:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5} 
""")

gabungan_tanpa_token_aspek = ulasan_1 + ulasan_2 + ulasan_3 + ulasan_4 + ulasan_5

# Penambahan token aspek
ulasan_1.extend(token_aspek)
ulasan_2.extend(token_aspek)
ulasan_3.extend(token_aspek)
ulasan_4.extend(token_aspek)
ulasan_5.extend(token_aspek)

print("="*130, '\n')
print(f"""Setelah Stopword Removal:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5}
""")

Sebelum Stopword Removal:
['senang', 'belanja', 'online', 'belanja', 'tidak_pernah', 'tertipu', 'penjualnya', 'jujur', 'ramah', 'layanan', 'pelanggan', 'sopan', 'kendala', 'beda', 'toko', 'online', 'shop', 'sebelah', 'tertipu', 'dionline', 'shop', 'sebelah', 'online', 'shope', 'nyaman', 'belanja', 'apapun', 'kesal', 'serbu', 'seru', 'belum_pernah', 'barang'] 

['aplikasi', 'bermanfaat', 'membantu', 'jaman', 'mudah', 'cepat'] 

['top', 'fitur', 'harganya', 'bermanfaat', 'sukses', 'bukalapak', 'excelent', 'nomor', 'wahid'] 

['pelayanan', 'bukalapak', 'penjual', 'jelek', 'bukadompet', 'dibekukan', 'komplain', 'berulang', 'bukti', 'transaksi', 'valid', 'dibekukan', 'hasil', 'penjualan', 'ditahan', 'mohon', 'aktifkan', 'bukadompet'] 

['bukalapak', 'bagus', 'barang', 'sesuai', 'pengiriman', 'cepat', 'tingkatkan', 'admin', 'biar', 'semangat', 'belanja', 'bukalapak', 'hahaha'] 


Setelah Stopword Removal:
['senang', 'belanja', 'online', 'belanja', 'tidak_pernah', 'tertipu', 'penjualnya', 'ju

**Pembangunan Kamus Corpus**

In [11]:
print(f"""Setelah Penambahan Token Aspek:
{ulasan_1} \n
{ulasan_2} \n
{ulasan_3} \n
{ulasan_4} \n
{ulasan_5}
""")

token_gabungan = ulasan_1 + ulasan_2 + ulasan_3 + ulasan_4 + ulasan_5

print("="*130, '\n')
print(f"""Gabungan Token:
{token_gabungan} 
""")

print(f"Panjang Token: {len(token_gabungan)}")

Setelah Penambahan Token Aspek:
['senang', 'belanja', 'online', 'belanja', 'tidak_pernah', 'tertipu', 'penjualnya', 'jujur', 'ramah', 'layanan', 'pelanggan', 'sopan', 'kendala', 'beda', 'toko', 'online', 'shop', 'sebelah', 'tertipu', 'dionline', 'shop', 'sebelah', 'online', 'shope', 'nyaman', 'belanja', 'apapun', 'kesal', 'serbu', 'seru', 'belum_pernah', 'barang', '<LAYANAN>', '<FITUR>', '<KEBERMANFAATAN>', '<BISNIS>', '<NON ASPEK>'] 

['aplikasi', 'bermanfaat', 'membantu', 'jaman', 'mudah', 'cepat', '<LAYANAN>', '<FITUR>', '<KEBERMANFAATAN>', '<BISNIS>', '<NON ASPEK>'] 

['top', 'fitur', 'harganya', 'bermanfaat', 'sukses', 'bukalapak', 'excelent', 'nomor', 'wahid', '<LAYANAN>', '<FITUR>', '<KEBERMANFAATAN>', '<BISNIS>', '<NON ASPEK>'] 

['pelayanan', 'bukalapak', 'penjual', 'jelek', 'bukadompet', 'dibekukan', 'komplain', 'berulang', 'bukti', 'transaksi', 'valid', 'dibekukan', 'hasil', 'penjualan', 'ditahan', 'mohon', 'aktifkan', 'bukadompet', '<LAYANAN>', '<FITUR>', '<KEBERMANFAATAN>'

In [12]:
# Formal
# kamus_corpus, index = {}, 1  # start indexing from 1
# kamus_corpus['<pad>'] = 0  # add a padding token

# for token in token_gabungan:
#     if token not in kamus_corpus:
#         kamus_corpus[token] = index
#         index += 1
        
# vocab_size = len(kamus_corpus)
# print(kamus_corpus)

# Buat Latihan
gabungan_tanpa_token_aspek.extend(token_aspek)
gabungan_tanpa_token_aspek.append("<UNKNOWN>")

index, kamus_corpus = 1, {}   # start indexing from 1
kamus_corpus['<pad>'] = 0  # add a padding token

for token in gabungan_tanpa_token_aspek:
    if token not in kamus_corpus:
        kamus_corpus[token] = index
        index += 1
        
vocab_size = len(kamus_corpus)
print(f"""Kamus Corpus: 
{kamus_corpus}""")

Kamus Corpus: 
{'<pad>': 0, 'senang': 1, 'belanja': 2, 'online': 3, 'tidak_pernah': 4, 'tertipu': 5, 'penjualnya': 6, 'jujur': 7, 'ramah': 8, 'layanan': 9, 'pelanggan': 10, 'sopan': 11, 'kendala': 12, 'beda': 13, 'toko': 14, 'shop': 15, 'sebelah': 16, 'dionline': 17, 'shope': 18, 'nyaman': 19, 'apapun': 20, 'kesal': 21, 'serbu': 22, 'seru': 23, 'belum_pernah': 24, 'barang': 25, 'aplikasi': 26, 'bermanfaat': 27, 'membantu': 28, 'jaman': 29, 'mudah': 30, 'cepat': 31, 'top': 32, 'fitur': 33, 'harganya': 34, 'sukses': 35, 'bukalapak': 36, 'excelent': 37, 'nomor': 38, 'wahid': 39, 'pelayanan': 40, 'penjual': 41, 'jelek': 42, 'bukadompet': 43, 'dibekukan': 44, 'komplain': 45, 'berulang': 46, 'bukti': 47, 'transaksi': 48, 'valid': 49, 'hasil': 50, 'penjualan': 51, 'ditahan': 52, 'mohon': 53, 'aktifkan': 54, 'bagus': 55, 'sesuai': 56, 'pengiriman': 57, 'tingkatkan': 58, 'admin': 59, 'biar': 60, 'semangat': 61, 'hahaha': 62, '<LAYANAN>': 63, '<FITUR>': 64, '<KEBERMANFAATAN>': 65, '<BISNIS>': 66

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
corpus = ['senang belanja online tidak_pernah tertipu penjualnya jujur ramah layanan pelanggan sopan kendala <LAYANAN> tertipu']
VEKTOR = vectorizer.fit_transform(token_gabungan)
print(vectorizer.get_feature_names_out())

panjang_vektor = len(vectorizer.get_feature_names_out())

print(VEKTOR.toarray())

print(panjang_vektor)



['admin' 'aktifkan' 'apapun' 'aplikasi' 'aspek' 'bagus' 'barang' 'beda'
 'belanja' 'belum_pernah' 'bermanfaat' 'berulang' 'biar' 'bisnis'
 'bukadompet' 'bukalapak' 'bukti' 'cepat' 'dibekukan' 'dionline' 'ditahan'
 'excelent' 'fitur' 'hahaha' 'harganya' 'hasil' 'jaman' 'jelek' 'jujur'
 'kebermanfaatan' 'kendala' 'kesal' 'komplain' 'layanan' 'membantu'
 'mohon' 'mudah' 'nomor' 'non' 'nyaman' 'online' 'pelanggan' 'pelayanan'
 'pengiriman' 'penjual' 'penjualan' 'penjualnya' 'ramah' 'sebelah'
 'semangat' 'senang' 'serbu' 'seru' 'sesuai' 'shop' 'shope' 'sopan'
 'sukses' 'tertipu' 'tidak_pernah' 'tingkatkan' 'toko' 'top' 'transaksi'
 'valid' 'wahid']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
66


In [14]:
# Pembuatan Korpus menggunakan 
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(token_gabungan)

training_korpus = tokenizer.texts_to_sequences(token_gabungan)

vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

print(training_korpus)

# training_korpus = tokenizer.texts_to_sequences(test_korpus)

word_index = tokenizer.word_index
print('\n')
print('Word Index: \n',word_index, '\n')

vocab_size = len(tokenizer.word_counts)
print(f"Panjang Korpus: {vocab_size} \n")

print(f"""Corpus :
{training_korpus}""")

68
[[19], [7], [9], [7], [20, 10], [11], [21], [22], [23], [1], [24], [25], [26], [27], [28], [9], [12], [13], [11], [29], [12], [13], [9], [30], [31], [7], [32], [33], [34], [35], [36, 10], [14], [1], [2], [3], [4], [5, 6], [37], [15], [38], [39], [40], [16], [1], [2], [3], [4], [5, 6], [41], [2], [42], [15], [43], [8], [44], [45], [46], [1], [2], [3], [4], [5, 6], [47], [8], [48], [49], [17], [18], [50], [51], [52], [53], [54], [18], [55], [56], [57], [58], [59], [17], [1], [2], [3], [4], [5, 6], [8], [60], [14], [61], [62], [16], [63], [64], [65], [66], [7], [8], [67], [1], [2], [3], [4], [5, 6]]


Word Index: 
 {'layanan': 1, 'fitur': 2, 'kebermanfaatan': 3, 'bisnis': 4, 'non': 5, 'aspek': 6, 'belanja': 7, 'bukalapak': 8, 'online': 9, 'pernah': 10, 'tertipu': 11, 'shop': 12, 'sebelah': 13, 'barang': 14, 'bermanfaat': 15, 'cepat': 16, 'bukadompet': 17, 'dibekukan': 18, 'senang': 19, 'tidak': 20, 'penjualnya': 21, 'jujur': 22, 'ramah': 23, 'pelanggan': 24, 'sopan': 25, 'kendala': 26,

In [22]:
# Hitung Word2Vec CBOW
# Konteks = pelayanan, target = jelek
x_w1 = np.array(([(0.295896048568338, 0.875116521258698, 0.349236435241011)]))
print('Matriks X * W1 = \n', x_w1, '\n')

wo = np.array(([0.888563979365201, 0.218313935186904, 0.580796934329850, 0.681545213455374, 0.927491847520756, 0.057652099980229, 0.964854706839704, 0.000570784865009, 0.781632570359999, 0.964367105429220, 0.098471988604675, 0.652514637920216, 0.610215722100892, 0.964043033160407, 0.535003013956565, 0.855455728652069, 0.716816837940844, 0.972308253104550, 0.117566238323095, 0.017978514903416, 0.114566126299784, 0.237463238883085, 0.297068781572555, 0.667025402287037, 0.558042551983460, 0.818564426814474, 0.140570123113170, 0.389408885580430, 0.541926876918667, 0.637492361665503, 0.120435535599047, 0.761205275353343, 0.072919409315591, 0.166073093004713, 0.316652429446665, 0.083219425917841, 0.931314438520837, 0.294830136424495, 0.291981827717498, 0.492446418745864, 0.307499481429108, 0.747951627690622, 0.414038647108478, 0.505714070395031, 0.843100793893863, 0.941210144199850, 0.632507187534394, 0.178042901444692, 0.782602892206363, 0.989205176606322, 0.967793286825441, 0.784785049188179, 0.797204574420512, 0.517966112648770, 0.171741490804255, 0.913320487158477, 0.922966041886655, 0.733539577861614, 0.656804549035976, 0.420937755432511, 0.761828746136406, 0.228489252387893, 0.390532826272719, 0.402222605074492, 0.961791113105603, 0.049410160338014, 0.453077906047781, 0.962461828896374],
[0.974344793589976,	0.751722890380824,	0.763469076083616,	0.304551547996851,	0.266194052059271,	0.544718234770658,	0.484716209030235,	0.715274222244976,	0.654541486157574,	0.636167560264755,	0.505765666445419,	0.318309637470674,	0.073483134048993,	0.337399718844010,	0.311282191443645,	0.087435107850281,	0.507966776354144,	0.461180240474609,	0.401530772902720,	0.728337941748544,	0.268489813158173,	0.889556241614190,	0.160452713841916,	0.798622281362812,	0.316890232224549,	0.051735862984310,	0.536946347309393,	0.461798503497999,	0.067020724134713,	0.432349817559332,	0.280191630821428,	0.239835813820470,	0.800880854805450,	0.270725850360651,	0.466526422802128,	0.191460058627431,	0.335043914238249,	0.721889536074550,	0.441002583816223,	0.130566990213852,	0.367033784265990,	0.897241650851948,	0.795304772873041,	0.078080145255067,	0.022585575514360,	0.603599614703498,	0.527312552458811,	0.848439522477953,	0.530950277591858,	0.659536477269735,	0.517126337014028,	0.174220711616174,	0.426183106005842,	0.498545071305308,	0.205441503854195,	0.253002970797249,	0.438193363626917,	0.593906752915362,	0.338847260716643,	0.171643679728545,	0.025088349305311,	0.008594709473533,	0.499375376368382,	0.744859738473849,	0.373017199247224,	0.957838871990445,	0.045550500039313,	0.822064789041146],
[0.529292105839121,	0.770768907365604,	0.716704240994275,	0.333990174273797,	0.328071866660900,	0.615717807054809,	0.833257819661222,	0.662527405812146,	0.127911795206998,	0.784794397354449,	0.166702010471746,	0.796402444086605,	0.522419049163537,	0.257642549222496,	0.458313554899391,	0.446523580738361,	0.031161283880481,	0.473591137687783,	0.320492824553229,	0.291320400350903,	0.567305641514417,	0.802240668029179,	0.272989987178495,	0.352542530479943,	0.867072540237627,	0.756553419099302,	0.816357786793103,	0.057480425733755,	0.573016702727897,	0.266712355406567,	0.494384140033599,	0.661991860064933,	0.422266789695167,	0.159985522405666,	0.960561030973873,	0.256921243921245,	0.830023862323862,	0.556622239685314,	0.261992023787515,	0.860443421991516,	0.935752898941041,	0.282287777370737,	0.930976656130412,	0.834003869129923,	0.768039567712267,	0.004591816217233,	0.388385660861922,	0.268289631916889,	0.007046112811189,	0.590923570806926,	0.253716820005544,	0.207409834878488,	0.878748391719332,	0.434988662136596,	0.685927767070524,	0.368389630523654,	0.642725453367186,	0.951115181431175,	0.520645685942289,	0.826746356219077,	0.866585417032627,	0.659977734955393,	0.588991718438790,	0.468734347180679,	0.443635953096195,	0.922646908133139,	0.223169234942836,	0.006727575370675]))

print('Wo = \n', wo,'\n')

# perkalian matriksnya
hasil_kali_matriks = np.dot(x_w1, wo)
print("hasil: \n", hasil_kali_matriks, '\n')
print("Dimensi Hasil Matriks", hasil_kali_matriks.shape)

Matriks X * W1 = 
 [[0.29589605 0.87511652 0.34923644]] 

Wo = 
 [[8.88563979e-01 2.18313935e-01 5.80796934e-01 6.81545213e-01
  9.27491848e-01 5.76521000e-02 9.64854707e-01 5.70784865e-04
  7.81632570e-01 9.64367105e-01 9.84719886e-02 6.52514638e-01
  6.10215722e-01 9.64043033e-01 5.35003014e-01 8.55455729e-01
  7.16816838e-01 9.72308253e-01 1.17566238e-01 1.79785149e-02
  1.14566126e-01 2.37463239e-01 2.97068782e-01 6.67025402e-01
  5.58042552e-01 8.18564427e-01 1.40570123e-01 3.89408886e-01
  5.41926877e-01 6.37492362e-01 1.20435536e-01 7.61205275e-01
  7.29194093e-02 1.66073093e-01 3.16652429e-01 8.32194259e-02
  9.31314439e-01 2.94830136e-01 2.91981828e-01 4.92446419e-01
  3.07499481e-01 7.47951628e-01 4.14038647e-01 5.05714070e-01
  8.43100794e-01 9.41210144e-01 6.32507188e-01 1.78042901e-01
  7.82602892e-01 9.89205177e-01 9.67793287e-01 7.84785049e-01
  7.97204574e-01 5.17966113e-01 1.71741491e-01 9.13320487e-01
  9.22966042e-01 7.33539578e-01 6.56804549e-01 4.20937755e-01
  7.6

Softmax

In [23]:
eksponensialkan = np.exp(hasil_kali_matriks)
print('Eksponensial : \n', eksponensialkan, '\n')

print(f"Sum Eksponensial: {np.sum(eksponensialkan)} ", '\n')

probabilitas_softmax = eksponensialkan / np.sum(eksponensialkan)
print('Probabilitas Softmax \n', probabilitas_softmax, '\n')

# Maka jika probabilitas masing-masing dijumlahkan hasilnya akan bernilai satu
probabilitas_softmax.sum()

Eksponensial : 
 [[3.67089641 2.69560842 2.97510447 1.79467898 1.86258747 2.03151546
  2.72014136 2.35725049 2.33673234 3.05308317 1.69886398 2.1165074
  1.53313474 1.95521225 1.8053839  1.6251241  1.9493891  2.35533719
  1.64559393 2.10526223 1.59517482 3.09225769 1.38216948 2.77147157
  2.10697188 1.73620363 2.21795732 1.71502269 1.5206278  1.93505086
  1.57380095 1.94704647 2.38669981 1.40766149 2.31040791 1.3256467
  2.35997093 2.49270708 1.75737651 1.75149984 2.09380758 3.01950255
  3.13813199 1.66401367 1.71165819 2.24414362 2.19077361 2.43236041
  2.01108268 2.93364364 2.28763645 1.57950782 2.49862484 2.09900421
  1.60024037 1.85950456 2.41339725 2.91232913 1.95953098 1.75679652
  1.73328863 1.35746462 2.13457194 2.5460783  2.15105311 3.23834634
  1.28642208 2.73611942]] 

Sum Eksponensial: 145.26216732349076  

Probabilitas Softmax 
 [[0.02527084 0.01855685 0.02048093 0.01235476 0.01282225 0.01398517
  0.01872574 0.01622756 0.01608631 0.02101774 0.01169516 0.01457026
  0.010554

1.0